workspace:
  clean: all

trigger: none # will disable CI builds entirely

variables:
  gitCreds: '$(secmircom.user):$(secmircom.pat)'

steps:
- checkout: self
  clean: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.x'
    architecture: 'x64'

- script: python -m pip install --upgrade pip
  displayName: 'Install/Upgrade pip'

- script: pip install -r requirements.txt --upgrade
  displayName: 'Install/Upgrade mu_build'

# Update dependencies
- task: PythonScript@0
  displayName: 'Update Dependencies'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'SharedCryptoPkg/DriverBuilder.py'
    arguments: '--UPDATE'
    failOnStderr: true

# Update dependencies (to resolve nugets from previously resolved ext_deps)
- task: PythonScript@0
  displayName: 'Update Dependencies (Again)'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'SharedCryptoPkg/DriverBuilder.py'
    arguments: '--UPDATE'
    failOnStderr: true


# Build and publish
- task: PythonScript@0
  displayName: 'Build and Ship'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'SharedCryptoPkg/DriverBuilder.py'
    arguments: '--dump-version'
    failOnStderr: true

# Publish Build Artifacts
# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  displayName: 'Publish NugetPackage'
  continueOnError: true
  condition: succeeded()
  inputs:
    pathtoPublish: 'Build/'
    artifactName: 'Nuget Package'
    targetFolder: $(Build.ArtifactStagingDirectory)

# publish to Nuget
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Uefibot_Mu_SharedCrypto'
    versioningScheme: byEnvVar
    versionEnvVar: NugetPackageVersion
